import registry from "./file-icons.json";
import { detectFileType, extensionOf, fileNameFromPath } from "./fileTypes";
import type { DocumentKind } from "./types";

/**
 * File type icons shared by tabs, the tab overflow menu and the settings preview.
 * `file-icons.json` is generated by `scripts/file-icons.mjs`; it already
 * resolves group and category fallbacks for every supported extension.
 */
export const FILE_ICON_THEME = registry.theme;

const fileNames: Record<string, string> = registry.fileNames;
const extensions: Record<string, string> = registry.extensions;
const categories: Record<string, string> = registry.categories;

function categoryIcon(kind: DocumentKind): string {
  if (kind === "markdown" || kind === "text") return categories.text;
  if (kind === "image") return categories.image;
  if (kind === "pdf") return categories.document;
  return categories.code;
}

/** Stored icon name for a file: exact file name, then extension, then its category. */
export function fileIconName(fileName: string): string {
  const baseName = fileNameFromPath(fileName).toLowerCase();
  if (Object.hasOwn(fileNames, baseName)) return fileNames[baseName];
  if (baseName.startsWith("dockerfile.")) return fileNames.dockerfile;
  if (baseName.startsWith(".env.")) return fileNames[".env"];
  const extension = extensionOf(baseName);
  if (extension && Object.hasOwn(extensions, extension)) return extensions[extension];
  return categoryIcon(detectFileType(baseName).kind);
}

/** App-relative URL of the 32 px preview image, rendered at 16 CSS pixels. */
export function fileIconUrl(fileName: string, base = ""): string {
  return `${base}/file-icons/${fileIconName(fileName)}.png`;
}
