// Windows installer hooks for the file associations in
// src/lib/files/associations.json. Pure functions without side effects, shared
// by `npm run sync:associations`, its `--check` mode, the unit tests and the
// registry test of the compiled hooks (scripts/test-installer-hooks.mjs).

/**
 * @typedef {{ progId: string, description: string, extensions: string[] }} AssociationGroup
 * @typedef {{ extensions: Record<string, string> }} IconRegistry
 * @typedef {{ appKey?: string, verbKey?: string, verbLabel?: string }} HookOptions
 * @typedef {{ group: AssociationGroup, extension: string, progId: string, icon: string }} AssociationEntry
 */

/** Group ProgIDs predate per-extension icons; they stay with the group's first extension. */
const EXTENSION_PROG_ID_PREFIX = "PViewer.File.";

const DEFAULT_HOOK_OPTIONS = Object.freeze({
  /** `Software\<appKey>` holds Capabilities; the app itself uses the same key. */
  appKey: "P-Viewer",
  /** Explorer verb key below `SystemFileAssociations\.<ext>\shell`. */
  verbKey: "PViewer",
  verbLabel: "Mit P-Viewer öffnen",
});

// NSIS escapes a quote inside a string as $\" -- an unknown `$"` is kept
// literally, which made every open command unusable before v0.2.1 (issue #7).
const OPEN_COMMAND = '"$\\"$INSTDIR\\${MAINBINARYNAME}.exe$\\" $\\"%1$\\""';
const APP_ICON = '"$INSTDIR\\${MAINBINARYNAME}.exe,0"';
const NOTIFY_SHELL = '  System::Call "shell32::SHChangeNotify(i,i,i,i) (0x08000000, 0x1000, 0, 0)"';

/**
 * @param {AssociationGroup} group
 * @param {string} extension
 */
function progIdFor(group, extension) {
  return extension === group.extensions[0] ? group.progId : `${EXTENSION_PROG_ID_PREFIX}${extension}`;
}

/**
 * @param {AssociationGroup[]} groups
 * @param {IconRegistry} registry
 * @returns {AssociationEntry[]}
 */
export function associationEntries(groups, registry) {
  return groups.flatMap((group) =>
    group.extensions.map((extension) => ({
      group,
      extension,
      progId: progIdFor(group, extension),
      icon: registry.extensions[extension],
    })),
  );
}

/** @param {string} value */
function escapeNsis(value) {
  return value
    .replace(/\$/g, () => "$$")
    .replace(/"/g, () => '$\\"')
    .replace(/[\r\n]+/g, " ");
}

/**
 * @param {AssociationGroup[]} groups
 * @param {IconRegistry} registry
 * @param {HookOptions} [options]
 */
export function renderNsisHooks(groups, registry, options = {}) {
  const { appKey, verbKey, verbLabel } = { ...DEFAULT_HOOK_OPTIONS, ...options };
  const entries = associationEntries(groups, registry);
  const verb = `Software\\Classes\\SystemFileAssociations\\.\${EXT}\\shell\\${verbKey}`;
  /** @type {(macro: string, args: string[]) => string} */
  const insert = (macro, args) => `  !insertmacro ${macro} ${args.map((arg) => `"${arg}"`).join(" ")}`;
  /** @type {(macro: string, args: (entry: AssociationEntry) => string[], list?: AssociationEntry[]) => string[]} */
  const perEntry = (macro, args, list = entries) => list.map((entry) => insert(macro, args(entry)));

  return [
    "; Generated by scripts/sync-file-associations.mjs. Do not edit manually.",
    "; Candidate-only registration: never writes an extension default or UserChoice.",
    "; Windows keeps the user's current default until it is confirmed in Settings.",
    "; Every extension has its own ProgID, so Explorer shows its file type icon",
    "; from $INSTDIR\\assets\\file-icons (issue #3). Besides \"Open with\" (OpenWithProgids",
    "; and Applications\\<exe>\\SupportedTypes) every supported extension gets an",
    `; explicit "${escapeNsis(verbLabel)}" verb below SystemFileAssociations (issue #7).`,
    "; Quotes inside values must be written as $\\\"; NSIS keeps other dollar escapes",
    "; as literal text, so warning 6000 (unknown variable) is an error in these hooks.",
    "",
    "!macro PVIEWER_REGISTER_PROGID PROGID DESCRIPTION ICON",
    '  WriteRegStr SHCTX "Software\\Classes\\${PROGID}" "" "${DESCRIPTION}"',
    '  WriteRegStr SHCTX "Software\\Classes\\${PROGID}\\DefaultIcon" "" "$INSTDIR\\assets\\file-icons\\${ICON}.ico"',
    `  WriteRegStr SHCTX "Software\\Classes\\\${PROGID}\\shell\\open\\command" "" ${OPEN_COMMAND}`,
    "!macroend",
    "",
    "!macro PVIEWER_UNREGISTER_PROGID PROGID",
    '  DeleteRegKey SHCTX "Software\\Classes\\${PROGID}"',
    "!macroend",
    "",
    "!macro PVIEWER_REGISTER_EXTENSION EXT PROGID GROUPPROGID",
    '  DeleteRegValue SHCTX "Software\\Classes\\.${EXT}" "${PROGID}_backup"',
    "  ; Earlier versions offered the group ProgID for every extension of a group.",
    '  StrCmp "${PROGID}" "${GROUPPROGID}" +2 0',
    '  DeleteRegValue SHCTX "Software\\Classes\\.${EXT}\\OpenWithProgids" "${GROUPPROGID}"',
    '  WriteRegStr SHCTX "Software\\Classes\\.${EXT}\\OpenWithProgids" "${PROGID}" ""',
    `  WriteRegStr SHCTX "Software\\${appKey}\\Capabilities\\FileAssociations" ".\${EXT}" "\${PROGID}"`,
    '  WriteRegStr SHCTX "Software\\Classes\\Applications\\${MAINBINARYNAME}.exe\\SupportedTypes" ".${EXT}" ""',
    "!macroend",
    "",
    "!macro PVIEWER_UNREGISTER_EXTENSION EXT PROGID GROUPPROGID",
    '  DeleteRegValue SHCTX "Software\\Classes\\.${EXT}\\OpenWithProgids" "${PROGID}"',
    '  DeleteRegValue SHCTX "Software\\Classes\\.${EXT}\\OpenWithProgids" "${GROUPPROGID}"',
    '  DeleteRegKey /ifempty SHCTX "Software\\Classes\\.${EXT}\\OpenWithProgids"',
    '  DeleteRegValue SHCTX "Software\\Classes\\Applications\\${MAINBINARYNAME}.exe\\SupportedTypes" ".${EXT}"',
    "!macroend",
    "",
    "; Explorer context menu entry for supported extensions only, never for `*`.",
    "!macro PVIEWER_REGISTER_CONTEXT_MENU EXT",
    `  WriteRegStr SHCTX "${verb}" "" "${escapeNsis(verbLabel)}"`,
    `  WriteRegStr SHCTX "${verb}" "Icon" ${APP_ICON}`,
    `  WriteRegStr SHCTX "${verb}\\command" "" ${OPEN_COMMAND}`,
    "!macroend",
    "",
    "; Removes only P-Viewer's verb; parent keys go only if nothing else is left.",
    "!macro PVIEWER_UNREGISTER_CONTEXT_MENU EXT",
    `  DeleteRegKey SHCTX "${verb}"`,
    '  DeleteRegKey /ifempty SHCTX "Software\\Classes\\SystemFileAssociations\\.${EXT}\\shell"',
    '  DeleteRegKey /ifempty SHCTX "Software\\Classes\\SystemFileAssociations\\.${EXT}"',
    "!macroend",
    "",
    "; Icons P-Viewer added to Windows-generated <ext>_auto_file classes are logged;",
    "; only values that are still unchanged are removed again.",
    "!macro PVIEWER_REMOVE_AUTO_FILE_ICONS",
    "  Push $R0",
    "  Push $R1",
    "  Push $R2",
    "  Push $R3",
    "  StrCpy $R0 0",
    "  pviewer_auto_file_loop:",
    `    EnumRegValue $R1 HKCU "Software\\${appKey}\\AutoFileIcons" $R0`,
    "    StrCmp $R1 \"\" pviewer_auto_file_done",
    `    ReadRegStr $R2 HKCU "Software\\${appKey}\\AutoFileIcons" $R1`,
    '    ReadRegStr $R3 HKCU "Software\\Classes\\$R1\\DefaultIcon" ""',
    "    StrCmp $R2 $R3 0 +2",
    '    DeleteRegKey HKCU "Software\\Classes\\$R1\\DefaultIcon"',
    "    IntOp $R0 $R0 + 1",
    "    Goto pviewer_auto_file_loop",
    "  pviewer_auto_file_done:",
    `  DeleteRegKey HKCU "Software\\${appKey}\\AutoFileIcons"`,
    "  Pop $R3",
    "  Pop $R2",
    "  Pop $R1",
    "  Pop $R0",
    "!macroend",
    "",
    "; Rewriting identical values keeps the user's default app choice, so every",
    "; install and update simply registers everything again (idempotent).",
    "!macro NSIS_HOOK_POSTINSTALL",
    "  !pragma warning push",
    "  !pragma warning error 6000",
    `  WriteRegStr SHCTX "Software\\${appKey}\\Capabilities" "ApplicationName" "\${PRODUCTNAME}"`,
    `  WriteRegStr SHCTX "Software\\${appKey}\\Capabilities" "ApplicationDescription" "Schneller Editor und Dokumentbetrachter"`,
    `  WriteRegStr SHCTX "Software\\${appKey}\\Capabilities" "ApplicationIcon" ${APP_ICON}`,
    `  WriteRegStr SHCTX "Software\\RegisteredApplications" "${appKey}" "Software\\${appKey}\\Capabilities"`,
    '  WriteRegStr SHCTX "Software\\Classes\\Applications\\${MAINBINARYNAME}.exe" "FriendlyAppName" "${PRODUCTNAME}"',
    `  WriteRegStr SHCTX "Software\\Classes\\Applications\\\${MAINBINARYNAME}.exe\\DefaultIcon" "" ${APP_ICON}`,
    `  WriteRegStr SHCTX "Software\\Classes\\Applications\\\${MAINBINARYNAME}.exe\\shell\\open\\command" "" ${OPEN_COMMAND}`,
    ...perEntry("PVIEWER_REGISTER_PROGID", (entry) => [entry.progId, escapeNsis(entry.group.description), entry.icon]),
    ...perEntry("PVIEWER_REGISTER_EXTENSION", (entry) => [entry.extension, entry.progId, entry.group.progId]),
    ...perEntry("PVIEWER_REGISTER_CONTEXT_MENU", (entry) => [entry.extension]),
    NOTIFY_SHELL,
    "  !pragma warning pop",
    "!macroend",
    "",
    "; An installer replacing this version (updater, reinstall or upgrade) runs the",
    "; uninstaller in place with _?= or with /UPDATE and registers everything again",
    "; right afterwards; a real uninstall runs from a temporary copy. Deleting the",
    "; ProgIDs in between would make Windows drop the user's default app for these",
    "; types (issue #7), so they are only removed by a real uninstall.",
    "!macro NSIS_HOOK_PREUNINSTALL",
    "  !pragma warning push",
    "  !pragma warning error 6000",
    "  ${If} $UpdateMode <> 1",
    "  ${AndIf} $EXEDIR != $INSTDIR",
    ...perEntry("PVIEWER_UNREGISTER_EXTENSION", (entry) => [entry.extension, entry.progId, entry.group.progId]),
    ...perEntry("PVIEWER_UNREGISTER_CONTEXT_MENU", (entry) => [entry.extension]),
    ...perEntry("PVIEWER_UNREGISTER_PROGID", (entry) => [entry.progId], [...entries].reverse()),
    "  !insertmacro PVIEWER_REMOVE_AUTO_FILE_ICONS",
    `  DeleteRegValue SHCTX "Software\\RegisteredApplications" "${appKey}"`,
    `  DeleteRegKey SHCTX "Software\\${appKey}\\Capabilities"`,
    `  DeleteRegKey /ifempty SHCTX "Software\\${appKey}"`,
    `  DeleteRegKey /ifempty HKCU "Software\\${appKey}"`,
    '  DeleteRegKey SHCTX "Software\\Classes\\Applications\\${MAINBINARYNAME}.exe"',
    NOTIFY_SHELL,
    "  ${EndIf}",
    "  !pragma warning pop",
    "!macroend",
    "",
  ].join("\n");
}

/**
 * @param {string} hooks
 * @param {string} name
 */
function macroBody(hooks, name) {
  return hooks.match(new RegExp(`^!macro ${name}\\b[^\\n]*\\n([\\s\\S]*?)^!macroend`, "m"))?.[1] ?? "";
}

/**
 * @param {string} body
 * @param {string} macro
 */
function insertions(body, macro) {
  return [...body.matchAll(new RegExp(`^\\s*!insertmacro ${macro} (.+)$`, "gm"))].map((match) => match[1]);
}

/**
 * Structural checks of generated hooks; returns the problems found. Guards the
 * invariants of issue #7 against later edits of the template above.
 * @param {string} hooks
 * @param {AssociationGroup[]} groups
 * @param {IconRegistry} registry
 * @param {HookOptions} [options]
 * @returns {string[]}
 */
export function verifyNsisHooks(hooks, groups, registry, options = {}) {
  const { verbKey } = { ...DEFAULT_HOOK_OPTIONS, ...options };
  const problems = [];
  const code = hooks.split("\n").filter((line) => !line.trimStart().startsWith(";"));
  const codeText = code.join("\n");

  if (/\$"/.test(codeText)) problems.push('Ein Wert enthält $" statt $\\" und wäre in der Registry unbrauchbar.');
  if (/UserChoice|FileExts/i.test(codeText)) problems.push("Die Hooks dürfen UserChoice/FileExts weder schreiben noch löschen.");
  for (const line of code) {
    // `Software\Classes\.<ext>` itself (its default is the handler) is Windows' business.
    if (/^\s*WriteReg\w+\s+\w+\s+"Software\\Classes\\\.[^"\\]*"/.test(line)) {
      problems.push(`Schreibt eine Standardzuordnung: ${line.trim()}`);
    }
    if (/^\s*DeleteRegKey\b.*"Software\\Classes\\\.[^"\\]*"/.test(line)) {
      problems.push(`Löscht eine ganze Dateiendung: ${line.trim()}`);
    }
    if (/"Software\\Classes\\\*\\/.test(line)) problems.push(`Registriert für alle Dateien (*): ${line.trim()}`);
    if (/\\shell\\open\\command"|\\command" ""/.test(line) && !line.trimEnd().endsWith(OPEN_COMMAND)) {
      problems.push(`Unerwarteter Öffnen-Befehl: ${line.trim()}`);
    }
  }

  /** @type {(name: string, fragments: string[]) => void} */
  const expectBody = (name, fragments) => {
    const body = macroBody(hooks, name);
    if (!body) problems.push(`Makro ${name} fehlt.`);
    for (const fragment of fragments) {
      if (body && !body.includes(fragment)) problems.push(`Makro ${name} enthält „${fragment}“ nicht.`);
    }
  };
  expectBody("PVIEWER_REGISTER_PROGID", ["\\shell\\open\\command"]);
  expectBody("PVIEWER_REGISTER_EXTENSION", ["\\OpenWithProgids\"", "\\SupportedTypes\""]);
  expectBody("PVIEWER_REGISTER_CONTEXT_MENU", [`\\shell\\${verbKey}\\command"`]);
  expectBody("PVIEWER_UNREGISTER_CONTEXT_MENU", [`DeleteRegKey SHCTX "Software\\Classes\\SystemFileAssociations\\.\${EXT}\\shell\\${verbKey}"`]);

  const install = macroBody(hooks, "NSIS_HOOK_POSTINSTALL");
  const uninstall = macroBody(hooks, "NSIS_HOOK_PREUNINSTALL");
  if (!install.includes("SHChangeNotify") || !uninstall.includes("SHChangeNotify")) {
    problems.push("Installation und Deinstallation müssen den Explorer benachrichtigen.");
  }
  if (!uninstall.includes("${If} $UpdateMode <> 1") || !uninstall.includes("${AndIf} $EXEDIR != $INSTDIR")) {
    problems.push("Die Deinstallation muss Updates und Neuinstallationen die Registrierung lassen.");
  }

  const expected = new Map();
  for (const entry of associationEntries(groups, registry)) {
    expected.set(`PVIEWER_REGISTER_PROGID:${entry.progId}`, entry.extension);
    expected.set(`PVIEWER_REGISTER_EXTENSION:"${entry.extension}" "${entry.progId}" "${entry.group.progId}"`, entry.extension);
    expected.set(`PVIEWER_REGISTER_CONTEXT_MENU:"${entry.extension}"`, entry.extension);
  }
  const pairs = [
    ["PVIEWER_REGISTER_PROGID", "PVIEWER_UNREGISTER_PROGID"],
    ["PVIEWER_REGISTER_EXTENSION", "PVIEWER_UNREGISTER_EXTENSION"],
    ["PVIEWER_REGISTER_CONTEXT_MENU", "PVIEWER_UNREGISTER_CONTEXT_MENU"],
  ];
  for (const [register, unregister] of pairs) {
    let registered = insertions(install, register);
    // A ProgID is removed by name only; compare the ProgID argument.
    if (register === "PVIEWER_REGISTER_PROGID") registered = registered.map((args) => args.split('" "')[0] + '"');
    const unregistered = insertions(uninstall, unregister);
    const seen = new Set();
    for (const args of registered) {
      if (seen.has(args)) problems.push(`${register} ${args} kommt doppelt vor.`);
      seen.add(args);
    }
    const missing = registered.filter((args) => !unregistered.includes(args));
    const extra = unregistered.filter((args) => !registered.includes(args));
    if (missing.length > 0 || extra.length > 0 || unregistered.length !== registered.length) {
      problems.push(`${register}/${unregister} sind nicht symmetrisch (fehlend: ${missing.join(", ") || "keine"}; zusätzlich: ${extra.join(", ") || "keine"}).`);
    }
    for (const args of seen) {
      const key = register === "PVIEWER_REGISTER_PROGID" ? `${register}:${args.slice(1, -1)}` : `${register}:${args}`;
      if (!expected.has(key)) problems.push(`${register} ${args} gehört zu keiner unterstützten Dateiendung.`);
    }
  }
  for (const [key, extension] of expected) {
    const [macro, args] = [key.slice(0, key.indexOf(":")), key.slice(key.indexOf(":") + 1)];
    const found = macro === "PVIEWER_REGISTER_PROGID"
      ? insertions(install, macro).some((line) => line.startsWith(`"${args}" `))
      : insertions(install, macro).includes(args);
    if (!found) problems.push(`.${extension}: ${macro} fehlt.`);
  }
  return problems;
}
